#!/bin/bash

#
# █▀▄▀█ ██   ▄█▄    ████▄    ▄▄▄▄▄
# █ █ █ █ █  █▀ ▀▄  █   █   █     ▀▄
# █ ▄ █ █▄▄█ █   ▀  █   █ ▄  ▀▀▀▀▄
# █   █ █  █ █▄  ▄▀ ▀████  ▀▄▄▄▄▀
#    █     █ ▀███▀
#   ▀     █
#        ▀ v 0.1a
# Made w/ <3 by Nicholas Adamou
# ~/.macos — https://github.com/dotbrains/macos
# Based on https://github.com/mathiasbynens/dotfiles/blob/master/.macos.

function preCheck() {
	# Close any open System Preferences panes, to prevent them from overriding
	# settings we’re about to change
	osascript -e 'tell application "System Preferences" to quit'

	# Ask for the administrator password up front
	sudo -v

	# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
	while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
}

function postCheck() {
	echo -e "###############################################################################
# Kill affected applications                                                  #
###############################################################################"

	# Kill all apps that were affected
	for app in "Activity Monitor" "cfprefsd" "Dock" "Finder" \
	           "Google Chrome" "iTunes" "Mail" "Messages" \
					   "Photos" "Safari" "SystemUIServer" "Terminal" \
						 "Transmission" "Tweetbot"; do
		killall "${app}" &> /dev/null
	done

	echo "[!] Done. Note that some of these changes require a logout/restart to take effect."
}

function begin() {
	preCheck

	echo ""
	sleep 0.2 && echo "█▀▄▀█ ██   ▄█▄    ████▄    ▄▄▄▄▄"
	sleep 0.2 && echo "█ █ █ █ █  █▀ ▀▄  █   █   █     ▀▄"
	sleep 0.2 && echo "█ ▄ █ █▄▄█ █   ▀  █   █ ▄  ▀▀▀▀▄"
	sleep 0.2 && echo "█   █ █  █ █▄  ▄▀ ▀████  ▀▄▄▄▄▀"
	sleep 0.2 && echo "   █     █ ▀███▀"
	sleep 0.2 && echo "  ▀     █"
	sleep 0.2 && echo "       ▀ v 0.1a"

	sleep 0.1
	echo "Made with <3 by: Nicholas Adamou (4d4m0u)"
	sleep 0.1
	# shellcheck disable=SC2088
	echo "~/.macos — https://github.com/dotbrains/macos"
	sleep 0.1
	echo "Based on https://github.com/mathiasbynens/dotfiles/blob/master/.macos."
	sleep 0.1
	echo ""

	#System Configuration(s)
	bash system/general
	bash system/input
	bash system/screen
	bash system/dock

	#App Configuration(s)
	bash apps/finder
	bash apps/iTunes
	bash apps/safari
	bash apps/mail
	bash apps/terminal
	bash apps/iTerm
	bash apps/time-machine
	bash apps/activity-monitor
	bash apps/textEdit
	bash apps/disk-utility
	bash apps/app-store
	bash apps/photos
	bash apps/messages
	bash apps/google-chrome
	bash apps/transmission

	postCheck
}

begin
