#!/bin/bash

echo -e "###############################################################################
# Dock, Dashboard, Mission Control and hot corners                            #
###############################################################################"

# Wipe all (default) app icons from the Dock
# This is only really useful when setting up a new Mac, or if you don’t use
# the Dock to launch apps.
#echo "[-] Wipe all (default) app icons from the Dock."
#defaults write com.apple.dock persistent-apps -array

# Set the icon size of Dock items to 36 pixels
#echo "[-] Set the icon size of Dock items to 36 pixels."
#defaults write com.apple.dock tilesize -int 36

# Show indicator lights for open applications in the Dock
echo "[-] Show indicator lights for open applications in the Dock."
defaults write com.apple.dock show-process-indicators -bool true

# Change minimize/maximize window effect
echo "[-] Change minimize/maximize window effect."
defaults write com.apple.dock mineffect -string "genie"

# Don't minimize windows into their application’s icon
echo "[-] Don't minimize windows into their application’s icon."
defaults write com.apple.dock minimize-to-application -bool false

# Remove the auto-hiding Dock delay
echo "[-] Remove the auto-hiding Dock delay."
defaults write com.apple.dock autohide-delay -float 0

# Remove the animation when hiding/showing the Dock
echo "[-] Remove the animation when hiding/showing the Dock."
defaults write com.apple.dock autohide-time-modifier -float 0

# Make Dock icons of hidden applications translucent
echo "[-] Make Dock icons of hidden applications translucent."
defaults write com.apple.dock showhidden -bool true

# Speed up dock show/hide animation
# http://bengold.tv/post/21711266050
echo "[-] Dock: Speed up dock show/hide animation."
defaults write com.apple.dock autohide-time-modifier -float 0.5

# Speed up Mission Control animations
echo "[-] Speed up Mission Control animations."
defaults write com.apple.dock expose-animation-duration -float 0.1

# Don’t show Dashboard as a Space
echo "[-] Don’t show Dashboard as a Space."
defaults write com.apple.dock dashboard-in-overlay -bool true

# Don’t automatically rearrange Spaces based on most recent use
echo "[-] Don’t automatically rearrange Spaces based on most recent use."
defaults write com.apple.dock mru-spaces -bool false

# Reset Launchpad, but keep the desktop wallpaper intact
#echo "[-] Reset Launchpad, but keep the desktop wallpaper intact."
#find "${HOME}/Library/Application Support/Dock" -name "*-*.db" -maxdepth 1 -delete

# Disable Dashboard
echo "[-] Disable Dashboard."
defaults write com.apple.dashboard mcx-disabled -bool true

# Hot Corners
# Possible values:
#  0: no-op
#  2: Mission Control
#  3: Show application windows
#  4: Desktop
#  5: Start screen saver
#  6: Disable screen saver
#  7: Dashboard
# 10: Put display to sleep
# 11: Launchpad
# 12: Notification Center
# Top left screen corner → Mission Control
#echo "[-] Set top left screen corner → Mission Control."
#defaults write com.apple.dock wvous-tl-corner -int 2
#defaults write com.apple.dock wvous-tl-modifier -int 0
# Top right screen corner → Desktop
#echo "[-] Set top right screen corner → Desktop."
#defaults write com.apple.dock wvous-tr-corner -int 4
#defaults write com.apple.dock wvous-tr-modifier -int 0
# Bottom left screen corner → Start screen saver
#echo "[-] Set bottom left screen corner → Start screen saver."
#defaults write com.apple.dock wvous-bl-corner -int 5
#defaults write com.apple.dock wvous-bl-modifier -int 0
