#!/bin/bash

echo -e "###############################################################################
# Activity Monitor                                                            #
###############################################################################"

# Show the main window when launching Activity Monitor
echo "[-] Show the main window when launching Activity Monitor."
defaults write com.apple.ActivityMonitor OpenMainWindow -bool true

# Visualize CPU usage in the Activity Monitor Dock icon
echo "[-] Visualize CPU usage in the Activity Monitor Dock icon."
defaults write com.apple.ActivityMonitor IconType -int 5

# Show all processes in Activity Monitor
echo "[-] Show all processes in Activity Monitor."
defaults write com.apple.ActivityMonitor ShowCategory -int 0

# Sort Activity Monitor results by CPU usage
echo "[-] Sort Activity Monitor results by CPU usage."
defaults write com.apple.ActivityMonitor SortColumn -string "CPUUsage"
defaults write com.apple.ActivityMonitor SortDirection -int 0
