#!/bin/bash

echo -e "###############################################################################
# iTerm 2                                                                     #
###############################################################################"

# Don’t display the annoying prompt when quitting iTerm
echo "[-] Don’t display the annoying prompt when quitting iTerm."
defaults write com.googlecode.iterm2 PromptOnQuit -bool false
