#!/bin/bash

echo -e "###############################################################################
# Terminal                                                                    #
###############################################################################"

# Enable “focus follows mouse” for Terminal.app and all X11 apps
# i.e. hover over a window and start typing in it without clicking first
#echo "[-] Enable “focus follows mouse” for Terminal.app and all X11 apps."
#defaults write com.apple.terminal FocusFollowsMouse -bool true
#defaults write org.x.X11 wm_ffm -bool true

# Only use UTF-8 in Terminal.app
echo "[-] Only use UTF-8 in Terminal.app."
defaults write com.apple.terminal StringEncodings -array 4

# Enable Secure Keyboard Entry in Terminal.app
# See: https://security.stackexchange.com/a/47786/8918
echo "[-] Enable Secure Keyboard Entry in Terminal.app."
defaults write com.apple.terminal SecureKeyboardEntry -bool true

# Disable the annoying line marks in Terminal.app
echo "[-] Disable the annoying line marks in Terminal.app."
defaults write com.apple.Terminal ShowLineMarks -int 0
