#!/bin/bash

echo -e "###############################################################################
# Transmission                                                                #
###############################################################################"

# Use `${HOME}/Documents/Torrents` to store incomplete downloads
echo -e "[-] Use \"${HOME}/Documents/@Torrents/@Incomplete\" to store incomplete downloads."
if [ ! -d "${HOME}/Documents/@Torrents/@Incomplete" ]; then
 mkdir -p ${HOME}/Documents/@Torrents/@Incomplete &> /dev/null
fi
defaults write org.m0k.transmission UseIncompleteDownloadFolder -bool true
defaults write org.m0k.transmission IncompleteDownloadFolder -string "${HOME}/Documents/@Torrents/@Incomplete"

# Don’t prompt for confirmation before downloading
echo "[-] Don’t prompt for confirmation before downloading."
defaults write org.m0k.transmission DownloadAsk -bool false
defaults write org.m0k.transmission MagnetOpenAsk -bool false

# Trash original torrent files
echo "[-] Trash original torrent files."
defaults write org.m0k.transmission DeleteOriginalTorrent -bool true

# Hide the donate message
echo "[-] Hide the donate message."
defaults write org.m0k.transmission WarningDonate -bool false

# Hide the legal disclaimer
echo "[-] Hide the legal disclaimer."
defaults write org.m0k.transmission WarningLegal -bool false

# Set IP block list.
# Source: https://giuliomac.wordpress.com/2014/02/19/best-blocklist-for-transmission/
echo "[-] Set IP block list."
defaults write org.m0k.transmission BlocklistNew -bool true
defaults write org.m0k.transmission BlocklistURL -string "http://john.bitsurge.net/public/biglist.p2p.gz"
defaults write org.m0k.transmission BlocklistAutoUpdate -bool true
