#!/bin/bash

echo -e "###############################################################################
# Tweetbot                                                                #
###############################################################################"

# Bypass the annoyingly slow t.co URL shortener
echo "[-] Bypass the annoyingly slow t.co URL shortener."
defaults write com.tapbots.TweetbotMac OpenURLsDirectly -bool true
